#!/bin/bash


echo "enter pose 1"
read -p "Press Enter..."

ros2 topic pub --once /joint_targets sensor_msgs/msg/JointState "{
  name: [\"elbow_1\", \"elbow_2\", \"elbow_3\", \"wrist_1\", \"wrist_2\"],
  position: [210, 60, 150, 85.0, 90.0],
  velocity: [600.0, 0.0, 600.0, 0.0, 0.0]
}"


echo "release front"
read -p "Press Enter..."

ros2 topic pub --once /joint_targets sensor_msgs/msg/JointState "{
  name: [\"elbow_1\", \"elbow_2\", \"elbow_3\", \"wrist_1\", \"wrist_2\"],
  position: [197.4, 62.27, 133.12, 85.0, 90.0],
  velocity: [300.0, 300.0, 300.0, 0.0, 0.0]
}"


ros2 topic pub --once /joint_targets sensor_msgs/msg/JointState "{
  name: [\"elbow_1\", \"elbow_2\", \"elbow_3\", \"wrist_1\", \"wrist_2\"],
  position: [229.05, 114.14, 112.19, 85.0, 90.0],
  velocity: [300.0, 600.0, 300.0, 0.0, 0.0]
}"


ros2 topic pub --once /joint_targets sensor_msgs/msg/JointState "{
  name: [\"elbow_1\", \"elbow_2\", \"elbow_3\", \"wrist_1\", \"wrist_2\"],
  position: [235.99, 111.98, 124.01, 85.0, 90.0],
  velocity: [150.0, 150.0, 150.0, 0.0, 0.0]
}"

echo "attatch"
read -p "Press Enter..."

ros2 service call /suction_control custom_msgs/srv/SuctionControl "{cup_1: 1, cup_2: 1}"

echo "detatch rear"
read -p "Press Enter..."

ros2 service call /suction_control custom_msgs/srv/SuctionControl "{cup_1: -1, cup_2: 1}"

echo "lifting rear leg "
read -p "Press Enter..."

ros2 topic pub --once /joint_targets sensor_msgs/msg/JointState "{
  name: [\"elbow_1\", \"elbow_2\", \"elbow_3\", \"wrist_1\", \"wrist_2\"],
  position: [246.81, 114.14, 131.95, 85.0, 90.0],
  velocity: [300.0, 300.0, 300.0, 0.0, 0.0]
}"

echo "pulling rear leg &normalise"
read -p "Press Enter..."

ros2 topic pub --once /joint_targets sensor_msgs/msg/JointState "{
  name: [\"elbow_1\", \"elbow_2\", \"elbow_3\", \"wrist_1\", \"wrist_2\"],
  position: [225.88, 62.27, 163.6, 85.0, 90.0],
  velocity: [300.0, 600.0, 300.0, 0.0, 0.0]
}"

ros2 service call /suction_control custom_msgs/srv/SuctionControl "{cup_1: 0, cup_2: 1}"

echo "pressing rear leg "
read -p "Press Enter..."

ros2 topic pub --once /joint_targets sensor_msgs/msg/JointState "{
  name: [\"elbow_1\", \"elbow_2\", \"elbow_3\", \"wrist_1\", \"wrist_2\"],
  position: [207.31, 59.14, 145.16, 85.0, 90.0],
  velocity: [150.0, 150.0, 150.0, 0.0, 0.0]
}"

echo "atatch"
read -p "Press Enter..."

ros2 service call /suction_control custom_msgs/srv/SuctionControl "{cup_1: 1, cup_2: 1}"

echo "Sequence complete."
