#!/usr/bin/bash

if [[ "$1" == "" ]]; then
    msg="{name: [\"elbow_1\", \"elbow_2\", \"elbow_3\"], 
        position: [$ELBOW_1, $ELBOW_2, $ELBOW_3], 
        velocity: [$VEL], 
        effort: [$ACC]}"
    ros2 topic pub --once /joint_targets sensor_msgs/msg/JointState "$msg"
fi

e1="$1"
e2="$2"
e3="$3"

v="$4"
a="$5"

default_vel = 0;
default_a = 0;

if [[ "$v" == ""]]; then
    v1 = $default_vel
fi
if [[ "$a" == ""]]; then 
    a = $default_a
fi


if [[ "$1" == "" ]]; then
    echo "Enter a joint number (1, 2 or 3)"
    exit 1
fi

a="$7"


# Construct and publish the message
msg="{name: [\"elbow_1\", \"elbow_2\", \"elbow_3\"], position: [$e1, $e2, $e3], velocity: [$v], effort: [$a]}"

ros2 topic pub --once /joint_targets sensor_msgs/msg/JointState "$msg"
